/* Santo Pecado 17-29 — Administración final integrada
   Complementa la interfaz existente sin reemplazarla. */
(function(){
  const URL='https://ghucwrrvqivmbogtcgcr.supabase.co';
  const KEY='sb_publishable_chFTmgoaIVvJSdpgTTuUSQ_fBNEq4WJ';
  const CDN='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';
  let db=null, me=null, products=[], categories=[], toppings=[], promotions=[];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(n||0));
  const safeDate=v=>{if(!v)return '';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,16)};
  const displayDate=v=>{if(!v)return 'Sin fecha';const d=new Date(v);return Number.isNaN(d.getTime())?'Fecha no válida':d.toLocaleString('es-CO')};
  const $=s=>document.querySelector(s);
  function toast(msg,ok=true){let x=$('#spAdminToast');if(!x){x=document.createElement('div');x.id='spAdminToast';document.body.appendChild(x)}x.textContent=msg;x.className='spToast '+(ok?'ok':'bad');clearTimeout(window.__spToast);window.__spToast=setTimeout(()=>x.remove(),3200)}
  function style(){if($('#spAdminStyle'))return;const s=document.createElement('style');s.id='spAdminStyle';s.textContent=`
#spAdminBtn{position:fixed;right:18px;bottom:18px;z-index:99990;border:0;border-radius:999px;padding:13px 17px;background:#111;color:#fff;font-weight:800;box-shadow:0 8px 30px #0005;cursor:pointer}
#spAdminOverlay{position:fixed;inset:0;background:#0009;z-index:99999;display:none;align-items:center;justify-content:center;padding:12px;font-family:inherit}
#spAdminPanel{width:min(1180px,100%);height:min(92vh,900px);background:#101010;color:#fff;border:1px solid #333;border-radius:22px;overflow:hidden;display:flex;flex-direction:column;box-shadow:0 30px 90px #000b}
.spAH{display:flex;align-items:center;justify-content:space-between;padding:15px 18px;border-bottom:1px solid #2b2b2b}.spAH h2{margin:0}.spAclose{border:0;background:#252525;color:#fff;border-radius:10px;padding:8px 12px;cursor:pointer}
.spTabs{display:flex;gap:7px;overflow:auto;padding:10px 14px;border-bottom:1px solid #282828}.spTabs button{border:1px solid #333;background:#191919;color:#ddd;border-radius:10px;padding:9px 12px;white-space:nowrap;cursor:pointer}.spTabs button.on{background:#fff;color:#111}
#spAdminBody{padding:14px;overflow:auto}.spGrid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px}.spCard{background:#171717;border:1px solid #292929;border-radius:16px;padding:13px}.spRow{display:flex;gap:8px;align-items:center;justify-content:space-between}.spMuted{color:#999;font-size:13px}.spActions{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.spBtn{border:0;border-radius:9px;padding:8px 10px;background:#2a2a2a;color:#fff;cursor:pointer}.spBtn.primary{background:#fff;color:#111;font-weight:800}.spBtn.danger{background:#5a1d1d}.spInput,.spSelect,.spTextarea{width:100%;box-sizing:border-box;background:#0d0d0d;border:1px solid #363636;color:#fff;border-radius:9px;padding:9px;margin-top:5px}.spTextarea{min-height:75px;resize:vertical}.spField{margin:8px 0}.spCheck{display:flex;align-items:center;gap:8px;margin-top:8px}.spThumb{width:64px;height:64px;border-radius:10px;object-fit:cover;background:#222}.spTable{width:100%;border-collapse:collapse}.spTable th,.spTable td{padding:8px;border-bottom:1px solid #292929;text-align:left;vertical-align:middle}.spTable th{color:#aaa;font-size:12px}.spPill{display:inline-block;padding:3px 7px;border-radius:999px;background:#243d2a;color:#a9e6b4;font-size:12px}.spPill.off{background:#402525;color:#ffb3b3}.spToast{position:fixed;right:18px;bottom:80px;z-index:100001;padding:12px 15px;border-radius:10px;background:#222;color:#fff;box-shadow:0 10px 30px #0006}.spToast.ok{border-left:4px solid #55d17a}.spToast.bad{border-left:4px solid #ff6262}
#spPromoBell{position:fixed;right:18px;top:18px;z-index:99980;border:0;border-radius:999px;padding:11px 14px;background:#fff;color:#111;font-weight:800;box-shadow:0 8px 25px #0004;cursor:pointer}
@media(max-width:700px){#spAdminBtn{right:10px;bottom:10px}.spTable{font-size:12px}.spHideMob{display:none!important}}
`;document.head.appendChild(s)}
  function shell(){if($('#spAdminOverlay'))return;const o=document.createElement('div');o.id='spAdminOverlay';o.innerHTML=`<div id="spAdminPanel"><div class="spAH"><div><div class="spMuted">SANTO PECADO 17-29</div><h2>Administración completa</h2></div><button class="spAclose" id="spClose">✕</button></div><div class="spTabs"><button data-t="products" class="on">🍔 Productos</button><button data-t="toppings">🧀 Toppings</button><button data-t="inventory">📦 Inventario</button><button data-t="promotions">🔥 Promociones</button><button data-t="notifications">🔔 Envíos</button></div><div id="spAdminBody"></div></div>`;document.body.appendChild(o);$('#spClose').onclick=()=>o.style.display='none';o.addEventListener('click',e=>{if(e.target===o)o.style.display='none'});o.querySelectorAll('.spTabs button').forEach(b=>b.onclick=()=>{o.querySelectorAll('.spTabs button').forEach(x=>x.classList.remove('on'));b.classList.add('on');renderTab(b.dataset.t)})}
  async function init(){style();if(!window.supabase){let sc=document.createElement('script');sc.src=CDN;sc.onload=init;document.head.appendChild(sc);return}db=window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});let {data:{user}}=await db.auth.getUser();if(user){const {data}=await db.from('app_users').select('*').eq('id',user.id).maybeSingle();me=data||null}if(me?.role==='admin'&&me.active){shell();let b=document.createElement('button');b.id='spAdminBtn';b.textContent='⚙️ Administración';b.onclick=async()=>{await refreshAll();$('#spAdminOverlay').style.display='flex';renderTab('products')};document.body.appendChild(b)};addCustomerPromotions()}
  async function refreshAll(){const [a,b,c,d]=await Promise.all([db.from('products').select('*').order('sort_order').order('name'),db.from('categories').select('*').order('sort_order').order('name'),db.from('toppings').select('*').order('name'),db.from('promotions').select('*,products(name)').order('created_at',{ascending:false})]);if(a.error)toast(a.error.message,false);products=a.data||[];categories=b.data||[];toppings=c.data||[];promotions=d.data||[]}
  function renderTab(t){if(t==='products')renderProducts();if(t==='toppings')renderToppings();if(t==='inventory')renderInventory();if(t==='promotions')renderPromotions();if(t==='notifications')renderNotifications()}
  function renderProducts(){const body=$('#spAdminBody');body.innerHTML=`<div class="spRow"><div><h3 style="margin:0">Productos</h3><div class="spMuted">Edita nombre, descripción, precio, categoría, stock, estado y fotografía.</div></div><button class="spBtn primary" onclick="window.SPAdmin.newProduct()">＋ Nuevo producto</button></div><div class="spGrid" style="margin-top:12px">${products.map(p=>`<div class="spCard"><div class="spRow"><div><b>${esc(p.name)}</b><div class="spMuted">${esc((categories.find(c=>c.id===p.category_id)||{}).name||'Sin categoría')}</div></div>${p.image_url?`<img class="spThumb" src="${esc(p.image_url)}">`:''}</div><div style="margin-top:8px"><b>${money(p.price)}</b> · Stock ${Number(p.stock||0)}</div><div class="spMuted">${esc(p.description||'Sin descripción')}</div><div class="spActions"><button class="spBtn" onclick="SPAdmin.editProduct('${p.id}')">✏️ Editar</button><button class="spBtn" onclick="SPAdmin.stockProduct('${p.id}')">📦 Stock</button><button class="spBtn" onclick="SPAdmin.toggleProduct('${p.id}')">${p.active?'Ocultar':'Activar'}</button></div></div>`).join('')}</div>`}
  function productForm(p){return `<div class="spCard"><div class="spField"><label>Nombre<input id="spf_name" class="spInput" value="${esc(p?.name||'')}"></label></div><div class="spField"><label>Categoría<select id="spf_cat" class="spSelect">${categories.map(c=>`<option value="${c.id}" ${c.id===p?.category_id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label></div><div class="spField"><label>Descripción<textarea id="spf_desc" class="spTextarea">${esc(p?.description||'')}</textarea></label></div><div class="spGrid"><div class="spField"><label>Precio<input id="spf_price" class="spInput" type="number" min="0" value="${Number(p?.price||0)}"></label></div><div class="spField"><label>Stock<input id="spf_stock" class="spInput" type="number" min="0" value="${Number(p?.stock||0)}"></label></div><div class="spField"><label>Stock mínimo<input id="spf_min" class="spInput" type="number" min="0" value="${Number(p?.minimum_stock||0)}"></label></div><div class="spField"><label>Orden<input id="spf_sort" class="spInput" type="number" value="${Number(p?.sort_order||0)}"></label></div></div><label class="spCheck"><input id="spf_active" type="checkbox" ${p?.active!==false?'checked':''}> Producto activo</label><div class="spField"><label>Fotografía<input id="spf_img" class="spInput" type="file" accept="image/*"></label></div><div class="spActions"><button class="spBtn primary" onclick="SPAdmin.saveProduct('${p?.id||''}')">💾 Guardar</button><button class="spBtn" onclick="SPAdmin.renderProducts()">Cancelar</button></div></div>`}
  async function editProduct(id){const p=products.find(x=>x.id===id);$('#spAdminBody').innerHTML=`<h3>Editar producto</h3>${productForm(p)}`}
  async function newProduct(){$('#spAdminBody').innerHTML=`<h3>Nuevo producto</h3>${productForm({active:true})}`}
  async function upload(file,folder){if(!file)return null;const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'');const path=folder+'/'+crypto.randomUUID()+'.'+ext;const {error}=await db.storage.from('product-images').upload(path,file,{upsert:false,contentType:file.type||'image/jpeg'});if(error)throw error;return db.storage.from('product-images').getPublicUrl(path).data.publicUrl}
  async function saveProduct(id){try{const payload={name:$('#spf_name').value.trim(),category_id:$('#spf_cat').value||null,description:$('#spf_desc').value.trim(),price:Number($('#spf_price').value||0),stock:Number($('#spf_stock').value||0),minimum_stock:Number($('#spf_min').value||0),sort_order:Number($('#spf_sort').value||0),active:$('#spf_active').checked,updated_at:new Date().toISOString()};if(!payload.name)throw Error('El producto necesita nombre.');const f=$('#spf_img').files[0];if(f)payload.image_url=await upload(f,'products');let error=null;if(id){let r=await db.rpc('admin_update_product',{p_product_id:id,p_name:payload.name,p_category_id:payload.category_id,p_description:payload.description,p_price:payload.price,p_stock:payload.stock,p_minimum_stock:payload.minimum_stock,p_sort_order:payload.sort_order,p_active:payload.active,p_image_url:payload.image_url??null});error=r.error;if(error){const fallback={...payload};delete fallback.updated_at;if(!f)delete fallback.image_url;const r2=await db.from('products').update(fallback).eq('id',id);error=r2.error}}else{const {error:e}=await db.from('products').insert(payload);error=e}if(error)throw error;const {data:check,error:checkError}=await db.from('products').select('id,name,description,price,stock,minimum_stock,sort_order,active,image_url,updated_at').eq('id',id).maybeSingle();if(id&&(checkError||!check||check.description!==payload.description||Number(check.price)!==payload.price||Number(check.stock)!==payload.stock||Number(check.minimum_stock)!==payload.minimum_stock||Number(check.sort_order)!==payload.sort_order||Boolean(check.active)!==payload.active)){throw Error('El servidor no confirmó todos los cambios del producto. No se ocultó el error.')}toast('Producto guardado y confirmado en Supabase');await refreshAll();renderProducts()}catch(e){toast(e.message||'No se pudo guardar',false)}}
  async function toggleProduct(id){const p=products.find(x=>x.id===id);const {error}=await db.from('products').update({active:!p.active,updated_at:new Date().toISOString()}).eq('id',id);if(error)toast(error.message,false);else{await refreshAll();renderProducts()}}
  async function stockProduct(id){const p=products.find(x=>x.id===id);const delta=prompt(`Stock actual: ${p.stock}\nEscribe la cantidad a sumar o restar. Ej: 10 o -3`);if(delta===null)return;const n=Number(delta);if(!Number.isFinite(n)||n===0)return toast('Cantidad no válida',false);const reason=prompt('Motivo del movimiento:');if(reason===null)return;const type=n>0?'entrada':'salida';const {error}=await db.rpc('adjust_product_stock',{p_product_id:id,p_delta:Math.trunc(n),p_movement_type:type,p_reason:reason});if(error)toast(error.message,false);else{toast('Inventario actualizado');await refreshAll();renderInventory()}}
  function renderToppings(){const b=$('#spAdminBody');b.innerHTML=`<div class="spRow"><div><h3 style="margin:0">Toppings y adiciones</h3><div class="spMuted">Precio, unidad, consumo por adición, stock y estado.</div></div><button class="spBtn primary" onclick="SPAdmin.newTopping()">＋ Nuevo topping</button></div><div class="spGrid" style="margin-top:12px">${toppings.map(t=>`<div class="spCard"><div class="spRow"><b>${esc(t.name)}</b><b>${Number(t.price)?money(t.price):'Gratis'}</b></div><div class="spMuted">${esc(t.unit)} · consume ${Number(t.consumption_per_addition)} · stock ${Number(t.stock)}</div><div class="spActions"><button class="spBtn" onclick="SPAdmin.editTopping('${t.id}')">✏️ Editar</button><button class="spBtn" onclick="SPAdmin.stockTopping('${t.id}')">📦 Inventario</button><button class="spBtn" onclick="SPAdmin.toggleTopping('${t.id}')">${t.active?'Ocultar':'Activar'}</button></div></div>`).join('')}</div>`}
  function toppingForm(t){return `<div class="spCard"><div class="spField"><label>Nombre<input id="spt_name" class="spInput" value="${esc(t?.name||'')}"></label></div><div class="spField"><label>Descripción<textarea id="spt_desc" class="spTextarea">${esc(t?.description||'')}</textarea></label></div><div class="spGrid"><div class="spField"><label>Precio<input id="spt_price" class="spInput" type="number" min="0" value="${Number(t?.price||0)}"></label></div><div class="spField"><label>Unidad<input id="spt_unit" class="spInput" value="${esc(t?.unit||'Porción')}"></label></div><div class="spField"><label>Consumo por adición<input id="spt_use" class="spInput" type="number" min="0" step="0.01" value="${Number(t?.consumption_per_addition||1)}"></label></div><div class="spField"><label>Stock<input id="spt_stock" class="spInput" type="number" min="0" step="0.01" value="${Number(t?.stock||0)}"></label></div></div><label class="spCheck"><input id="spt_active" type="checkbox" ${t?.active!==false?'checked':''}> Topping activo</label><div class="spActions"><button class="spBtn primary" onclick="SPAdmin.saveTopping('${t?.id||''}')">💾 Guardar</button><button class="spBtn" onclick="SPAdmin.renderToppings()">Cancelar</button></div></div>`}
  function editTopping(id){$('#spAdminBody').innerHTML=`<h3>Editar topping</h3>${toppingForm(toppings.find(x=>x.id===id))}`};function newTopping(){$('#spAdminBody').innerHTML=`<h3>Nuevo topping</h3>${toppingForm({active:true,unit:'Porción',consumption_per_addition:1})}`}
  async function saveTopping(id){try{const payload={name:$('#spt_name').value.trim(),description:$('#spt_desc').value.trim(),price:Number($('#spt_price').value||0),unit:$('#spt_unit').value.trim()||'Porción',consumption_per_addition:Number($('#spt_use').value||1),stock:Number($('#spt_stock').value||0),active:$('#spt_active').checked,updated_at:new Date().toISOString()};if(!payload.name)throw Error('El topping necesita nombre.');let error=null;if(id){const r=await db.rpc('admin_update_topping',{p_topping_id:id,p_name:payload.name,p_description:payload.description,p_price:payload.price,p_unit:payload.unit,p_consumption_per_addition:payload.consumption_per_addition,p_stock:payload.stock,p_minimum_stock:0,p_active:payload.active});error=r.error}else{const r=await db.from('toppings').insert(payload);error=r.error}if(error)throw error;const {data:check,error:checkError}=await db.from('toppings').select('id,name,description,price,unit,consumption_per_addition,stock,active,updated_at').eq('id',id).maybeSingle();if(id&&(checkError||!check||check.name!==payload.name||Number(check.price)!==payload.price||Number(check.stock)!==payload.stock||Number(check.consumption_per_addition)!==payload.consumption_per_addition||Boolean(check.active)!==payload.active)){throw Error('Supabase no confirmó todos los cambios del topping.');}toast('Topping guardado y confirmado en Supabase');await refreshAll();renderToppings()}catch(e){toast(e.message||'No se pudo guardar',false)}}
  async function toggleTopping(id){const t=toppings.find(x=>x.id===id);const {error}=await db.from('toppings').update({active:!t.active,updated_at:new Date().toISOString()}).eq('id',id);if(error)toast(error.message,false);else{await refreshAll();renderToppings()}}
  async function stockTopping(id){const t=toppings.find(x=>x.id===id);const delta=prompt(`Stock actual: ${t.stock} ${t.unit}\nCantidad a sumar o restar:`);if(delta===null)return;const n=Number(delta);if(!Number.isFinite(n)||n===0)return toast('Cantidad no válida',false);const reason=prompt('Motivo del movimiento:');if(reason===null)return;const type=n>0?'entrada':'salida';const {error}=await db.rpc('adjust_topping_stock',{p_topping_id:id,p_delta:n,p_movement_type:type,p_reason:reason});if(error)toast(error.message,false);else{toast('Inventario actualizado');await refreshAll();renderInventory()}}
  function renderInventory(){const b=$('#spAdminBody');b.innerHTML=`<div class="spRow"><div><h3 style="margin:0">Inventario</h3><div class="spMuted">Control por producto terminado y por topping/adición. Cada movimiento queda auditado.</div></div></div><h4>Productos</h4><table class="spTable"><thead><tr><th>Producto</th><th>Stock</th><th>Mínimo</th><th></th></tr></thead><tbody>${products.map(p=>`<tr><td>${esc(p.name)}</td><td><b>${Number(p.stock)}</b></td><td>${Number(p.minimum_stock)}</td><td><button class="spBtn" onclick="SPAdmin.stockProduct('${p.id}')">Ajustar</button></td></tr>`).join('')}</tbody></table><h4 style="margin-top:20px">Toppings</h4><table class="spTable"><thead><tr><th>Topping</th><th>Stock</th><th>Consumo</th><th></th></tr></thead><tbody>${toppings.map(t=>`<tr><td>${esc(t.name)}</td><td><b>${Number(t.stock)}</b> ${esc(t.unit)}</td><td>${Number(t.consumption_per_addition)}</td><td><button class="spBtn" onclick="SPAdmin.stockTopping('${t.id}')">Ajustar</button></td></tr>`).join('')}</tbody></table>`}
  function renderPromotions(){const b=$('#spAdminBody');b.innerHTML=`<div class="spRow"><div><h3 style="margin:0">Promociones</h3><div class="spMuted">Crea ofertas 2x1, descuento o precio especial y envíalas a los clientes registrados.</div></div><button class="spBtn primary" onclick="SPAdmin.newPromotion()">＋ Nueva promoción</button></div><div class="spGrid" style="margin-top:12px">${promotions.map(p=>`<div class="spCard"><div class="spRow"><b>${esc(p.name)}</b><span class="spPill ${p.active?'':'off'}">${p.active?'Activa':'Inactiva'}</span></div><div class="spMuted">${esc(p.products?.name||'Todos los productos')} · ${esc(p.offer_type)}</div><div style="margin-top:7px">${esc(p.description||'')}</div><div class="spMuted" style="margin-top:6px">Inicio: ${displayDate(p.starts_at)}${p.ends_at?' · Fin: '+displayDate(p.ends_at):''}</div><div class="spActions"><button class="spBtn" onclick="SPAdmin.editPromotion('${p.id}')">✏️ Editar</button><button class="spBtn primary" onclick="SPAdmin.sendPromotion('${p.id}')">📣 Enviar a clientes</button><button class="spBtn" onclick="SPAdmin.togglePromotion('${p.id}')">${p.active?'Desactivar':'Activar'}</button><button class="spBtn danger" onclick="SPAdmin.deletePromotion('${p.id}')">Eliminar</button></div></div>`).join('')}</div>`}
  function promoForm(p){return `<div class="spCard"><div class="spField"><label>Nombre<input id="spp_name" class="spInput" value="${esc(p?.name||'')}"></label></div><div class="spField"><label>Descripción<textarea id="spp_desc" class="spTextarea">${esc(p?.description||'')}</textarea></label></div><div class="spGrid"><div class="spField"><label>Producto<select id="spp_product" class="spSelect"><option value="">Todos</option>${products.map(x=>`<option value="${x.id}" ${x.id===p?.product_id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label></div><div class="spField"><label>Tipo<select id="spp_type" class="spSelect"><option value="2x1" ${p?.offer_type==='2x1'?'selected':''}>2x1</option><option value="descuento" ${p?.offer_type==='descuento'?'selected':''}>Descuento</option><option value="precio_especial" ${p?.offer_type==='precio_especial'?'selected':''}>Precio especial</option></select></label></div><div class="spField"><label>% descuento<input id="spp_discount" class="spInput" type="number" min="0" max="100" value="${Number(p?.discount_percent||0)}"></label></div><div class="spField"><label>Precio especial<input id="spp_special" class="spInput" type="number" min="0" value="${Number(p?.special_price||0)}"></label></div></div><div class="spGrid"><div class="spField"><label>Inicio<input id="spp_start" class="spInput" type="datetime-local" value="${safeDate(p?.starts_at)}"></label></div><div class="spField"><label>Fin<input id="spp_end" class="spInput" type="datetime-local" value="${safeDate(p?.ends_at)}"></label></div></div><label class="spCheck"><input id="spp_active" type="checkbox" ${p?.active!==false?'checked':''}> Promoción activa</label><div class="spField"><label>Imagen<input id="spp_img" class="spInput" type="file" accept="image/*"></label></div><div class="spActions"><button class="spBtn primary" onclick="SPAdmin.savePromotion('${p?.id||''}')">💾 Guardar</button><button class="spBtn" onclick="SPAdmin.renderPromotions()">Cancelar</button></div></div>`}
  function editPromotion(id){$('#spAdminBody').innerHTML=`<h3>Editar promoción</h3>${promoForm(promotions.find(x=>x.id===id))}`};function newPromotion(){const a=new Date();const b=new Date(a.getTime()+7*86400000);$('#spAdminBody').innerHTML=`<h3>Nueva promoción</h3>${promoForm({active:true,offer_type:'2x1',starts_at:a.toISOString(),ends_at:b.toISOString()})}`}
  async function savePromotion(id){try{const payload={name:$('#spp_name').value.trim(),description:$('#spp_desc').value.trim(),product_id:$('#spp_product').value||null,offer_type:$('#spp_type').value,discount_percent:Number($('#spp_discount').value||0)||null,special_price:Number($('#spp_special').value||0)||null,starts_at:$('#spp_start').value?new Date($('#spp_start').value).toISOString():null,ends_at:$('#spp_end').value?new Date($('#spp_end').value).toISOString():null,active:$('#spp_active').checked,updated_at:new Date().toISOString()};if(!payload.name)throw Error('La promoción necesita nombre.');const f=$('#spp_img').files[0];if(f)payload.image_url=await upload(f,'promotions');const {error}=id?await db.from('promotions').update(payload).eq('id',id):await db.from('promotions').insert(payload);if(error)throw error;toast('Promoción guardada');await refreshAll();renderPromotions()}catch(e){toast(e.message||'No se pudo guardar',false)}}
  async function togglePromotion(id){const p=promotions.find(x=>x.id===id);const {error}=await db.from('promotions').update({active:!p.active,updated_at:new Date().toISOString()}).eq('id',id);if(error)toast(error.message,false);else{await refreshAll();renderPromotions()}}
  async function deletePromotion(id){if(!confirm('¿Eliminar esta promoción?'))return;const {error}=await db.from('promotions').delete().eq('id',id);if(error)toast(error.message,false);else{toast('Promoción eliminada');await refreshAll();renderPromotions()}}
  async function sendPromotion(id){if(!confirm('¿Enviar esta promoción a todos los clientes registrados?'))return;const {data,error}=await db.rpc('notify_promotion_to_customers',{p_promotion_id:id});if(error)toast(error.message,false);else toast(`Aviso preparado para ${Number(data||0)} clientes registrados. La entrega al teléfono requiere Push/WhatsApp configurado.`)}
  async function renderNotifications(){const {data,error}=await db.from('customer_notifications').select('id,title,message,created_at,customer_id,promotion_id').order('created_at',{ascending:false}).limit(100);if(error)return toast(error.message,false);const b=$('#spAdminBody');b.innerHTML=`<div class="spRow"><div><h3 style="margin:0">Envíos a clientes</h3><div class="spMuted">Historial de notificaciones de promociones.</div></div></div><table class="spTable" style="margin-top:12px"><thead><tr><th>Fecha</th><th>Promoción</th><th>Mensaje</th></tr></thead><tbody>${(data||[]).map(n=>`<tr><td>${new Date(n.created_at).toLocaleString('es-CO')}</td><td>${esc(n.title)}</td><td>${esc(n.message)}</td></tr>`).join('')||'<tr><td colspan="3">Aún no hay envíos.</td></tr>'}</tbody></table>`}
  async function addCustomerPromotions(){try{const {data}=await db.from('promotions').select('*').eq('active',true).order('created_at',{ascending:false});const fresh=(data||[]).filter(p=>!localStorage.getItem('sp_seen_promo_'+p.id));if(!fresh.length)return;let b=document.createElement('button');b.id='spPromoBell';b.textContent=`🔥 ${fresh.length} promoción${fresh.length>1?'es':''}`;b.onclick=()=>{fresh.forEach(p=>localStorage.setItem('sp_seen_promo_'+p.id,'1'));alert(fresh.map(p=>`${p.name}\n${p.description||'Nueva promoción en Santo Pecado 17-29'}`).join('\n\n'));b.remove()};document.body.appendChild(b)}catch(e){console.warn('Promociones:',e)}}
  window.SPAdmin={editProduct,newProduct,saveProduct,toggleProduct,stockProduct,renderProducts,editTopping,newTopping,saveTopping,toggleTopping,stockTopping,renderToppings,renderInventory,editPromotion,newPromotion,savePromotion,togglePromotion,deletePromotion,sendPromotion,renderPromotions,renderNotifications};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();

window.printComanda = function(no){
  try{
    const list=JSON.parse(localStorage.getItem('ORDERS')||'[]');
    const o=list.find(x=>String(x.no)===String(no));
    if(!o){alert('No encontramos el pedido en este dispositivo.');return}

    const safe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
    const logo=document.querySelector('.brandLogo')?.src||'';
    const cleanLine=x=>String(x||'').replace(/\s+—\s+\$[\d.,]+/g,'').replace(/\s+\+\$[\d.,]+/g,'');
    const lines=String(o.detail||'').split('\n').map(x=>x.trim()).filter(Boolean).map(x=>'<div class="line">'+safe(cleanLine(x))+'</div>').join('');
    const date=new Date(o.created).toLocaleString('es-CO',{dateStyle:'short',timeStyle:'short'});
    const driver=o.type==='Domicilio'&&o.driverName?'<div><b>Domiciliario:</b> '+safe(o.driverName)+'</div>':'';

    const html='<!doctype html><html><head><meta charset="utf-8"><title>Comanda '+safe(o.no)+'</title><style>@page{size:80mm auto;margin:0}*{box-sizing:border-box}html,body{margin:0;padding:0;background:#fff;color:#111;font-family:Arial,Helvetica,sans-serif}body{width:80mm}.ticket{width:80mm;padding:4mm 4mm 5mm}.head{text-align:center;border-bottom:1px dashed #111;padding-bottom:3mm}.logo{display:block;width:30mm;height:auto;max-height:24mm;object-fit:contain;margin:0 auto 2mm}.brand{font-size:16px;font-weight:900}.title{text-align:center;font-size:14px;font-weight:900;margin:3mm 0}.info{font-size:10px;line-height:1.45;border-bottom:1px dashed #111;padding-bottom:3mm}.info div{margin-bottom:1mm;overflow-wrap:anywhere}.items{padding:3mm 0;border-bottom:1px dashed #111}.itemsTitle{font-size:12px;font-weight:900;margin-bottom:2mm}.line{font-size:11px;line-height:1.45;margin:1.5mm 0;white-space:pre-wrap;overflow-wrap:anywhere}.obs{font-size:10px;line-height:1.45;margin-top:3mm}.foot{text-align:center;font-size:9px;font-weight:900;margin-top:4mm}</style></head><body><div class="ticket"><div class="head">'+(logo?'<img class="logo" src="'+safe(logo)+'" alt="Santo Pecado">':'')+'<div class="brand">SANTO PECADO 17-29</div></div><div class="title">🍳 COMANDA DE COCINA<br>'+safe(o.no)+'</div><div class="info"><div><b>Hora:</b> '+safe(date)+'</div><div><b>Cliente:</b> '+safe(o.name||'No registrado')+'</div><div><b>Tipo:</b> '+safe(o.type||'')+'</div>'+(o.type==='Domicilio'&&o.addr?'<div><b>Dirección:</b> '+safe(o.addr)+'</div>':'')+driver+'</div><div class="items"><div class="itemsTitle">PREPARAR</div>'+(lines||'<div class="line">Sin productos</div>')+'</div>'+(o.obs?'<div class="obs"><b>OBSERVACIONES:</b><br>'+safe(o.obs)+'</div>':'')+'<div class="foot">PEDIDO RECIBIDO · PREPARAR</div></div></body></html>';

    const w=window.open('','_blank','width=420,height=800');
    if(!w){
      alert('Chrome bloqueó la ventana de la comanda. Permite ventanas emergentes para santopecado17-29.com y vuelve a pulsar Comanda cocina.');
      return;
    }
    w.document.open();
    w.document.write(html);
    w.document.close();
    setTimeout(()=>{try{w.focus();w.print();}catch(e){console.warn('Impresión no disponible:',e)}},500);

    const q=JSON.parse(localStorage.getItem('KITCHEN_QUEUE')||'[]');
    const item=q.find(x=>String(x.no)===String(no));
    if(item){
      item.printed=true;
      item.printedAt=new Date().toISOString();
      item.printedBy='administrador';
      localStorage.setItem('KITCHEN_QUEUE',JSON.stringify(q));
    }
  }catch(e){
    console.error('Comanda cocina:',e);
    alert('No se pudo abrir la comanda. Recarga la página y vuelve a intentarlo.');
  }
};
